theme: jekyll-theme-cayman
title: Learning English for Kids!
description: This website is designed to provide an introduction to the English language for early beginner learners. The target audience will be children from ages 5 to 12 years old. The site will include different activities, exercises, and multimedia that the user can interact with to keep them engaged on each page. 
github: 
  page2: alphabetandnumbers.html
  page3: weekdaysmonthsandtime.html
  page4: peopleplacesandthings.html
  page5: foodandbeverages.html
  page6: verbs.html
