theme: jekyll-theme-cayman
title: Kaia's Example
description: example of github
github: 
  page2: alphabetandnumbers.html
  page3: weekdaysmonthsandtime.html
  page4: peopleplacesandthings.html
  page5: foodandbeverages.html
  page6: verbs.html
