theme: jekyll-theme-cayman
title: Learning English for Kids!
description: An interactive and fun website for kids to learn English!
github: 
  page2: alphabetandnumbers.html
  page3: weekdaysmonthsandtime.html
  page4: peopleplacesandthings.html
  page5: foodandbeverages.html
  page6: verbs.html
